/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab;

public class Library {
	public static void main(String arg[]) {
		System.out.println("New Function");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
